<a href="https://colab.research.google.com/github/ankit-kr6/LEARNING-ML/blob/main/video_34.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!kaggle datasets download -d daniilmiroshnichenko/orders-csv

Dataset URL: https://www.kaggle.com/datasets/daniilmiroshnichenko/orders-csv
License(s): apache-2.0
Downloading orders-csv.zip to /content
100% 68.8k/68.8k [00:00<00:00, 459kB/s]

In [4]:
import zipfile
with zipfile.ZipFile('orders-csv.zip', 'r') as zip_ref:
    zip_ref.extractall('/content')

In [5]:
import pandas as pd
import numpy as np

In [6]:
date=pd.read_csv('orders.csv')

In [7]:
date.head()

       id  order_date ship_mode customer_id    sales
0  100006  2014-09-07  Standard    DK-13375  377.970
1  100090  2014-07-08  Standard    EB-13705  699.192
2  100293  2014-03-14  Standard    NF-18475   91.056
3  100328  2014-01-28  Standard    JC-15340    3.928
4  100363  2014-04-08  Standard    JM-15655   21.376

In [8]:
date['order_date']=pd.to_datetime(date['order_date'])

In [9]:
date['date_year']=date['order_date'].dt.year
date.head()

       id order_date ship_mode customer_id    sales  date_year
0  100006 2014-09-07  Standard    DK-13375  377.970       2014
1  100090 2014-07-08  Standard    EB-13705  699.192       2014
2  100293 2014-03-14  Standard    NF-18475   91.056       2014
3  100328 2014-01-28  Standard    JC-15340    3.928       2014
4  100363 2014-04-08  Standard    JM-15655   21.376       2014

       id order_date ship_mode customer_id    sales  date_year  date_day
0  100006 2014-09-07  Standard    DK-13375  377.970       2014         7
1  100090 2014-07-08  Standard    EB-13705  699.192       2014         8
2  100293 2014-03-14  Standard    NF-18475   91.056       2014        14
3  100328 2014-01-28  Standard    JC-15340    3.928       2014        28
4  100363 2014-04-08  Standard    JM-15655   21.376       2014         8

In [11]:
date['date_month']=date['order_date'].dt.month
date.head()

,id,order_date,ship_mode,customer_id,sales,date_year,date_day,date_month
0,100006,2014-09-07,Standard,DK-13375,377.970,2014,7,9
1,100090,2014-07-08,Standard,EB-13705,699.192,2014,8,7
2,100293,2014-03-14,Standard,NF-18475,91.056,2014,14,3
3,100328,2014-01-28,Standard,JC-15340,3.928,2014,28,1
4,100363,2014-04-08,Standard,JM-15655,21.376,2014,8,4

In [13]:
date['date_month_name']=date['order_date'].dt.month_name()
date.head()

,id,order_date,ship_mode,customer_id,sales,date_year,date_day,date_month,date_month_name
0,100006,2014-09-07,Standard,DK-13375,377.970,2014,7,9,September
1,100090,2014-07-08,Standard,EB-13705,699.192,2014,8,7,July
2,100293,2014-03-14,Standard,NF-18475,91.056,2014,14,3,March
3,100328,2014-01-28,Standard,JC-15340,3.928,2014,28,1,January
4,100363,2014-04-08,Standard,JM-15655,21.376,2014,8,4,April

In [14]:
#day of week
date['date_day_of_week']=date['order_date'].dt.dayofweek
date.head()

,id,order_date,ship_mode,customer_id,sales,date_year,date_day,date_month,date_month_name,date_day_of_week
0,100006,2014-09-07,Standard,DK-13375,377.970,2014,7,9,September,6
1,100090,2014-07-08,Standard,EB-13705,699.192,2014,8,7,July,1
2,100293,2014-03-14,Standard,NF-18475,91.056,2014,14,3,March,4
3,100328,2014-01-28,Standard,JC-15340,3.928,2014,28,1,January,1
4,100363,2014-04-08,Standard,JM-15655,21.376,2014,8,4,April,1

In [15]:
#day of week - name
date['date_day_of_week_name']=date['order_date'].dt.day_name()
date.head()

,id,order_date,ship_mode,customer_id,sales,date_year,date_day,date_month,date_month_name,date_day_of_week,date_day_of_week_name
0,100006,2014-09-07,Standard,DK-13375,377.970,2014,7,9,September,6,Sunday
1,100090,2014-07-08,Standard,EB-13705,699.192,2014,8,7,July,1,Tuesday
2,100293,2014-03-14,Standard,NF-18475,91.056,2014,14,3,March,4,Friday
3,100328,2014-01-28,Standard,JC-15340,3.928,2014,28,1,January,1,Tuesday
4,100363,2014-04-08,Standard,JM-15655,21.376,2014,8,4,April,1,Tuesday

In [16]:
#is weekend
date['is_weekend']=np.where(date['date_day_of_week_name'].isin(['Sunday','Saturday']),1,0)
date.head()

,id,order_date,ship_mode,customer_id,sales,date_year,date_day,date_month,date_month_name,date_day_of_week,date_day_of_week_name,is_weekend
0,100006,2014-09-07,Standard,DK-13375,377.970,2014,7,9,September,6,Sunday,1
1,100090,2014-07-08,Standard,EB-13705,699.192,2014,8,7,July,1,Tuesday,0
2,100293,2014-03-14,Standard,NF-18475,91.056,2014,14,3,March,4,Friday,0
3,100328,2014-01-28,Standard,JC-15340,3.928,2014,28,1,January,1,Tuesday,0
4,100363,2014-04-08,Standard,JM-15655,21.376,2014,8,4,April,1,Tuesday,0

In [23]:
#extract week of the year
date['date_week'] = date['order_date'].dt.isocalendar().week
date.head()

,id,order_date,ship_mode,customer_id,sales,date_year,date_day,date_month,date_month_name,date_day_of_week,date_day_of_week_name,is_weekend,date_week
0,100006,2014-09-07,Standard,DK-13375,377.970,2014,7,9,September,6,Sunday,1,36
1,100090,2014-07-08,Standard,EB-13705,699.192,2014,8,7,July,1,Tuesday,0,28
2,100293,2014-03-14,Standard,NF-18475,91.056,2014,14,3,March,4,Friday,0,11
3,100328,2014-01-28,Standard,JC-15340,3.928,2014,28,1,January,1,Tuesday,0,5
4,100363,2014-04-08,Standard,JM-15655,21.376,2014,8,4,April,1,Tuesday,0,15